### ISSUE TITLE
Неправильное создание пользователей

### ISSUE THREAD

**Issue by IgorZyktin** [IgorZyktin/Omoide#85]
На этапе присвоения коневой записи происходит попытка перезаписи пользователя.

**Comment by IgorZyktin** [comment]
```
Traceback (most recent call last):
  File "/home/omoide/omoide/manage.py", line 114, in <module>
    cli()
  File "/home/omoide/omoide/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/omoide/omoide/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/omoide/omoide/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/omoide/omoide/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/omoide/omoide/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/omoide/omoide/manage.py", line 53, in cmd_create_user
    asyncio.run(_coro())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/omoide/omoide/manage.py", line 45, in _coro
    result = await use_case.execute(dep.get_authenticator(), raw_user)
  File "/home/omoide/omoide/omoide/use_cases/api/uc_api_users.py", line 62, in execute
    await self.users_repo.update_user(user)
  File "/home/omoide/omoide/omoide/storage/repositories/asyncpg/rp_users.py", line 68, in update_user
    return await self.db.execute(stmt)
  File "/home/omoide/omoide/venv/lib/python3.10/site-packages/databases/core.py", line 170, in execute
    return await connection.execute(query, values)
  File "/home/omoide/omoide/venv/lib/python3.10/site-packages/databases/core.py", line 295, in execute
    return await self._connection.execute(built_query)
  File "/home/omoide/omoide/venv/lib/python3.10/site-packages/databases/backends/postgres.py", line 213, in execute
    return await self._connection.fetchval(query_str, *args)
  File "/home/omoide/omoide/venv/lib/python3.10/site-packages/asyncpg/connection.py", line 644, in fetchval
    data = await self._execute(query, args, 1, timeout)
  File "/home/omoide/omoide/venv/lib/python3.10/site-packages/asyncpg/connection.py", line 1658, in _execute
    result, _ = await self.__execute(
  File "/home/omoide/omoide/venv/lib/python3.10/site-packages/asyncpg/connection.py", line 1683, in __execute
    return await self._do_execute(
  File "/home/omoide/omoide/venv/lib/python3.10/site-packages/asyncpg/connection.py", line 1730, in _do_execute
    result = await executor(stmt, None)
  File "asyncpg/protocol/protocol.pyx", line 201, in bind_execute
asyncpg.exceptions.UniqueViolationError: duplicate key value violates unique constraint "users_login_key"
DETAIL:  Key (login)=(xxx) already exists.
```
